// <auto-generated />
using System;
using ConectaRiesgoAI.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConectaRiesgoAI.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816022824_AgregaIdentidadCanalReporte")]
    partial class AgregaIdentidadCanalReporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.EventoCronologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("eventos_cronologia", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Web");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AfectacionPropia");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Confianza")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Autorreportado");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentificadorCanal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UbicacionTexto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UrlFoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Estado");

                    b.HasIndex("Municipio");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Canal", "ReferenciaExterna")
                        .IsUnique()
                        .HasFilter("\"ReferenciaExterna\" IS NOT NULL");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsAcreditadoCenso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OrigenRegistro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Web");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ciudadano@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Ana Ciudadana",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Ciudadano"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gestor@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Carlos Gestor",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Gestor"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Admin Sistema",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.VerificacionSatelital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ConsultadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("DistanciaMasCercanaKm")
                        .HasColumnType("double precision");

                    b.Property<int>("FocosDetectados")
                        .HasColumnType("integer");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("verificaciones_satelitales", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.EventoCronologia", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Cronologia")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.VerificacionSatelital", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Reporte", "Reporte")
                        .WithMany("VerificacionesSatelitales")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("Cronologia");

                    b.Navigation("VerificacionesSatelitales");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
