// <auto-generated />
using System;
using ConectaRiesgoAI.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConectaRiesgoAI.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.DanoRegistrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalesPerdidos")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("EsPropietario")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("HectareasAfectadas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PersonaAfectadaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoInmueble")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaAfectadaId");

                    b.ToTable("danos_registrados", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.EventoCronologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("eventos_cronologia", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.MiembroNucleoFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<bool?>("EstudiaActualmente")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PersonaAfectadaId")
                        .HasColumnType("integer");

                    b.Property<bool>("TieneDiscapacidad")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaAfectadaId");

                    b.ToTable("miembros_nucleo_familiar", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.OperacionCenso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbiertaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BarrioVereda")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("BrigadistaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CerradaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("BrigadistaId", "Municipio")
                        .IsUnique()
                        .HasDatabaseName("IX_operaciones_censo_BrigadistaId_Municipio_Abierta")
                        .HasFilter("\"CerradaEn\" IS NULL");

                    b.ToTable("operaciones_censo", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.PersonaAfectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Comuna")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ConsentimientoDatos")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclaracionVeracidad")
                        .HasColumnType("boolean");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DireccionResidencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("EsAdultoMayor")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsCabezaDeHogar")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsResidenteDelMunicipio")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsVictimaConflicto")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaEmbarazada")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaDeclaracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ObservacionesSalud")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperacionCensoId")
                        .HasColumnType("integer");

                    b.Property<string>("PerteneceGrupoEtnico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAtencionMedica")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SincronizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoAlterno")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TieneDiscapacidad")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("ReporteId");

                    b.HasIndex("OperacionCensoId", "NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_personas_afectadas_OperacionCensoId_NumeroDocumento")
                        .HasFilter("\"NumeroDocumento\" IS NOT NULL");

                    b.ToTable("personas_afectadas", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Web");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AfectacionPropia");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Confianza")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Autorreportado");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IdentificadorCanal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UbicacionTexto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UrlFoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Estado");

                    b.HasIndex("Municipio");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Canal", "ReferenciaExterna")
                        .IsUnique()
                        .HasDatabaseName("IX_reportes_Canal_ReferenciaExterna")
                        .HasFilter("\"ReferenciaExterna\" IS NOT NULL");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsAcreditadoCenso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OrigenRegistro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Web");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasDatabaseName("IX_usuarios_Telefono");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ciudadano@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Ana Ciudadana",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Ciudadano"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gestor@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Carlos Gestor",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Gestor"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@conectariesgoai.demo",
                            EsAcreditadoCenso = false,
                            Municipio = "Bogotá",
                            Nombre = "Admin Sistema",
                            OrigenRegistro = "Web",
                            PasswordHash = "$2b$12$08eRl6W5Vpj8HwNAAQ3NUOUQOM.aG/NA.WTBc5LbMWjN9jz.3mwJ.",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.VerificacionSatelital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ConsultadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("DistanciaMasCercanaKm")
                        .HasColumnType("double precision");

                    b.Property<int>("FocosDetectados")
                        .HasColumnType("integer");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("verificaciones_satelitales", (string)null);
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.DanoRegistrado", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.PersonaAfectada", "PersonaAfectada")
                        .WithMany("Danos")
                        .HasForeignKey("PersonaAfectadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaAfectada");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.EventoCronologia", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Cronologia")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.MiembroNucleoFamiliar", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.PersonaAfectada", "PersonaAfectada")
                        .WithMany("NucleoFamiliar")
                        .HasForeignKey("PersonaAfectadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaAfectada");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.OperacionCenso", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Usuario", "Brigadista")
                        .WithMany()
                        .HasForeignKey("BrigadistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brigadista");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.PersonaAfectada", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.OperacionCenso", "OperacionCenso")
                        .WithMany("PersonasAfectadas")
                        .HasForeignKey("OperacionCensoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Reporte", "Reporte")
                        .WithMany()
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OperacionCenso");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.VerificacionSatelital", b =>
                {
                    b.HasOne("ConectaRiesgoAI.Api.Domain.Entities.Reporte", "Reporte")
                        .WithMany("VerificacionesSatelitales")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.OperacionCenso", b =>
                {
                    b.Navigation("PersonasAfectadas");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.PersonaAfectada", b =>
                {
                    b.Navigation("Danos");

                    b.Navigation("NucleoFamiliar");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("Cronologia");

                    b.Navigation("VerificacionesSatelitales");
                });

            modelBuilder.Entity("ConectaRiesgoAI.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
